### ISSUE TITLE
При попытке отправки чего-либо в кавычках вылетает всё

### ISSUE THREAD

**Issue by BANOnotIT** [vk-cli/vk#100]
У меня ubuntu 16.04, fish 2.2.0, ну и собственно сам vk 0.7.6. При попытке отправки чего-либо с кавычками вылетает какая-то ошибка, которую не получается понять.
![image](https://user-images.githubusercontent.com/11363215/30558211-56b5c65c-9cb9-11e7-82b2-3b44bd952743.png)

Проведя немного тестов заметил: английский текст внутри кавычек вполне себе уживается, но отправлять я пока не пытался, а вот как только я пытаюсь туда вставить русский, то он вылетает с такими вот непонятными символами.

**Comment by x0wllaar** [comment]
А это просто ncurses не может в юникод. Там вроде писались спецкостыли для того, чтобы починить это, но работают не всегда

**Comment by BANOnotIT** [comment]
А какая ncurses разница, что у него между кавычек? Он те же самые символы совершенно спокойно умеет без кавычек, а тут с чего-то ему захотелось вылететь...

**Comment by x0wllaar** [comment]
@BANOnotIT 
![image](https://user-images.githubusercontent.com/10964379/30561370-71b1192a-9cc3-11e7-84ff-1cc6e5e7257f.png)
Если в вводить как "-потом текст-", то все работает
А вот если поставить сразу 2, а потом вставлять между ними, то там происходит какой-то мисалайнмент в массиве из-за того, что у юникодных и не юникодных символов разный размер в байтах

**Comment by substanceof** [comment]
Я старался максимально класть все строки в wstring, который utf16 и всегда двухбайтовый. (у Д в фобосе вообще плохо с utf8, куча проблем) Но в интерфейсе, наверное, по сей день осталась куча utf8 string. Не знаю, будет ли это править @HaCk3Dq

**Comment by HaCk3Dq** [comment]
@x0wllaar этот баг еще с самых первых версий

там проблема во вставке символа, конверсия неправильно проходит, но фиксить это - ад

[https://github.com/vk-cli/vk/blob/master/source/app.d#L772](вот кусок)
