### ISSUE TITLE
DUB

### ISSUE THREAD

**Issue by substanceof** [vk-cli/vk#101]
Тут я обращаюсь к тем, кто каким-то чудом оказался подписан на этот репо. 
Кто-нибудь знает, почему dub убрали из реп арча и положили в аур?

**Comment by bcskda** [comment]
В Gentoo и Raspbian его и не было, например.

**Comment by bcskda** [comment]
Поиск по пакетам [говорит](https://www.archlinux.org/packages/community/x86_64/dub/), что есть

**Comment by substanceof** [comment]
Вернулся. До этого исчезал, ну да ладно
