### ISSUE TITLE
Глобальные уведомления беседы отображаются через раз

### ISSUE THREAD

**Issue by BANOnotIT** [vk-cli/vk#103]
Вот сейчас почему-то оказалось, что уведомления о приглашении человека и выходе его из беседы работают через раз.
Вот как оно на самом деле:
![image](https://user-images.githubusercontent.com/11363215/30879061-0e614832-a307-11e7-8fe5-fb1e6ca53f57.png)
А вот как показывается в консоли:
![image](https://user-images.githubusercontent.com/11363215/30879106-277ffa02-a307-11e7-8121-905376a00ff6.png)

**Comment by substanceof** [comment]
Валится на парсере, может быть
Нужен лог после проблемы

**Comment by BANOnotIT** [comment]
Блин, поздновато посмотрел. На будущее: где лог лежать должен?

**Comment by substanceof** [comment]
/tmp/vkcli-log

**Comment by BANOnotIT** [comment]
Вот есть лог, я там заменил id пользователей и беседы, надеюсь не порезал то, что важно для починки, если нужно, то у меня остался ещё оригинальный кусок.
[test.log](https://github.com/vk-cli/vk/files/1353161/test.log)
