### ISSUE TITLE
Логи в /tmp открыты для всех

### ISSUE THREAD

**Issue by denizzzka** [vk-cli/vk#107]
Права позволяют читать логи с чувствительными данными любому локальному пользователю.

**Comment by HaCk3Dq** [comment]
А я говорил @substanceof  не логать "чувствительные" данные, насколько я помню там и мессаджи и еще куча всего

**Comment by denizzzka** [comment]
логать можно - надо только про права не забывать :-)

**Comment by HaCk3Dq** [comment]
ну и это тоже)

**Comment by substanceof** [comment]
take two

**Comment by substanceof** [comment]
Теперь то точно непробиваемый костыль
https://github.com/vk-cli/vk/commit/538226d22001f45f3c9dca20e8848ce55b724278#diff-a74ecac7b048f9d9f1ef51ff1c4af11dR86

**Comment by substanceof** [comment]
Теперь то точно непробиваемый костыль
https://github.com/vk-cli/vk/blob/538226d22001f45f3c9dca20e8848ce55b724278/source/utils.d#L86

**Comment by denizzzka** [comment]
Ага. Жаль в фобосе почему-то не предусмотрели задачу прав для вновь открываемых файлов.

**Comment by substanceof** [comment]
Предусмотрели бы еще адекватный gc, который не оставляет треды в дедлоке из-за недошедшего сигнала..
Но это уже другая история

**Comment by denizzzka** [comment]
> из-за недошедшего сигнала..

А вы не думали что это ваш обработчик SIGUSRов их скрадывает? Так-то сигналы не могут не доходить.

**Comment by substanceof** [comment]
Проблема была задолго до появления обработчика. Чтобы хоть как-то решить проблему, я поменял сигналы на два SIGRT. Стало лучше, но полностью не решает. 
https://github.com/vk-cli/vk/blob/538226d22001f45f3c9dca20e8848ce55b724278/source/utils.d#L366-L376

**Comment by denizzzka** [comment]
Вообще не надо их трогать, имхо. Можно попробовать наоборот: их не менять, а для музыки использовать эти вот SIGRTMIN?

**Comment by x0wllaar** [comment]
И просрать совместимость с нелинуксами? Не надо важный функционал на SIGRT* завязывать, они же не POSIX

**Comment by substanceof** [comment]
@denizzzka Так их никто и не трогал в первых версиях, обработчиков для музыки не было. А проблема была и частично решилась sigrt
@x0wllaar Этот кусок кода собирается тольео на линуксе: `version(linux) {}`
