### ISSUE TITLE
Картинки!

### ISSUE THREAD

**Issue by denizzzka** [vk-cli/vk#108]
Сделал такую библиотеку:
![screenshot](https://user-images.githubusercontent.com/974632/31428083-c0580cbe-ae93-11e7-9940-62b0e6821f32.png)

Покажите как прямоугольный блок текста в чат вывести? А я бы уже туда показ картинок вкрячил.

Сам попробовал - ничего не понял в этом вашем API.

**Comment by denizzzka** [comment]
(Да, она без внешних зависимостей)

**Comment by HaCk3Dq** [comment]
что за терминал и покажи что ты выводишь?

**Comment by denizzzka** [comment]
Любой текстовый юникодный:
https://github.com/denizzzka/dtiv

**Comment by HaCk3Dq** [comment]
я пока без линукс тачки, так что вряд ли смогу протестить или впилить в тентакль

**Comment by denizzzka** [comment]
Ок ну пиши если что.

**Comment by substanceof** [comment]
Я попробую (хотя не по гуям).
Для идентейшона у нас как раз был костыль, для пересланых сообщений и мультилайна

**Comment by substanceof** [comment]
нужно еще запилить префетч и кеш для вложений. У мпв то есть свои network routines, тут же надо поработать

**Comment by denizzzka** [comment]
Вот я тут начал (и закончил). Здесь видно как можно построчно выводить в ANSI кодах терминала:
https://github.com/denizzzka/vk/tree/img_display

Если чего-то не хватает - говорите, допилю. Там ещё профилированием скорость конвертации раза в полтора-два можно поднять будет, думаю.

В виндах этот клиент работает? Виндовая консоль юникодные символы умеет выводить? Если да то там тоже можно сделать такой вывод. (Только там какой-то другой способ задания знакоместам цвета используется.)

**Comment by pvarenik** [comment]
@denizzzka может, конечно, дело в моем конекшене, но оригинальный клиент работает. Когда твоим открываю беседу с картинками, то валится `Connection lost: httpget`

**Comment by denizzzka** [comment]
> может, конечно, дело в моем конекшене, но оригинальный клиент работает. Когда твоим открываю беседу с картинками, то валится Connection lost: httpget

У меня показывает. Но: то что тут https://github.com/denizzzka/vk/tree/img_display абсолютно неюзабельно - код vk-cli я не понимаю. Это только для разработчиков, чтобы они не тратили время на понимание того как пользоваться этой библиотекой для вывода картинок.
