### ISSUE TITLE
Ошибка компиляции на Windows 10

### ISSUE THREAD

**Issue by alexandrov-va** [vk-cli/vk#109]
Выполняю dub build в master, и тут такая ошибка:

```
Running pre-generate commands for vk...
version string: 0.7.6-master-541f820
Performing "debug" build using dmd for x86.
ncurses ~master: target for configuration "minimal" is up to date.
vk ~master: building configuration "debug"...
source\musicplayer.d(377,18): Error: none of the overloads of 'kill' are callable using argument types (int, int), candidates are:
C:\D\dmd2\windows\bin\..\..\src\phobos\std\process.d(1774,6):        std.process.kill(Pid pid)
C:\D\dmd2\windows\bin\..\..\src\phobos\std\process.d(1785,6):        std.process.kill(Pid pid, int codeOrSignal)
source\musicplayer.d(402,16): Error: undefined identifier `UnixAddress`
source\utils.d(356,5): Error: undefined identifier `sigset`
source\utils.d(357,5): Error: undefined identifier `sigset`
Reticulating splines...
dmd failed with exit code 1.
```

**Comment by bcskda** [comment]
В винде нет UDS, конечно.
Платформонезависимая прослойка для сокетов?

**Comment by x0wllaar** [comment]
Cygwin? WSL?

**Comment by bcskda** [comment]
Хотя доки phobos [не описывают](https://dlang.org/phobos/std_socket.html#.AddressFamily) ```AdressFamily = UNIX``` как платформо-зависимый.

**Comment by substanceof** [comment]
Сигналы я конечно поправил, а с сокетами не знаю как быть. Сам mpv, в теории, поддерживает виндовые сокеты, но их надо поддерживать нам))

**Comment by bcskda** [comment]
@aubstanceof в принципе можно попробовать просить напрямую WinAPI, чтобы нативность 10/10

**Comment by punkew** [comment]
@alexandrov-va вообще, у меня получалось запускать вк на Винде, но более старые версии, может сможешь их найти

**Comment by substanceof** [comment]
Вообще, поддержка винды никакими костылями никогда не заявлялась. И я не вижу практической необходимости в этом клиенте под виндой. То, что старые версии каким-то боком работали на десятке - счастливая случайность. 
Так что в ближайшее время никаких шагов в этом направлении не будет
