### ISSUE TITLE
Сместить "название"/"новые сообщения" из центра в левую сторону

### ISSUE THREAD

**Issue by BANOnotIT** [vk-cli/vk#110]
Пользуюсь клинтом на весь экран, если честно, то вообще просто его запускаю в tty отдельном. И заметил такую вещь: читаю какой-нибудь диалог, сверху что-то мигнуло, я поднимаю глаза в левый верхний угол и пытаюсь найти, где же мигает.
В общем проблема такая: все элементы управления и все имена позиционированы относительно левой части экрана, и только этот "тайтл" выбивается и просто где-то посередине стоит.
Предложение заключается в том, чтобы убрать эту центровку.

**Comment by substanceof** [comment]
Может стоит просто выключить в настройках глобальные уведомления?

**Comment by BANOnotIT** [comment]
Не, в том то и прикол, что уведомления то нужны, просто когда поднимаешь взгляд, видишь там пустоту, а само уведомление идёт в середине. То есть нужно взгляд вправо перемещать. А хотелось бы, чтобы "мигнуло", и не нужно было искать эту строчку, которая иногда успевает пропасть, пока ищешь её.

**Comment by HaCk3Dq** [comment]
Изменения в ui части имеют слишком большой порог вхождения)
