### ISSUE TITLE
Сборка под арм

### ISSUE THREAD

**Issue by DTsurkov** [vk-cli/vk#111]
Добрый день!
А есть ли способ поставить на raspberry? Для него нет dmd просто...

**Comment by substanceof** [comment]
Ну же, сборка под малину ничем не отличается от сборки под любой другой арм.
Но это проблема. Дмд нету под арм, но есть ldc и gdc. Они в некоторых моментах несовместимы с дмд, так что я не уверен, собирается ли под ними последняя версия/мастер. Я проверю

**Comment by DTsurkov** [comment]
у меня собрать с помощью gdc не получается =/


`
pi@rpi:~/vk $ sudo dub build
Performing "debug" build using gdc for arm, arm_hardfloat.
ncurses ~master: target for configuration "minimal" is up to date.
vk ~master: building configuration "debug"...
source/utils.d:26: error: module vkversion is in file 'vkversion.d' which cannot be read
import path[0] = /usr/include/d/4.9/arm-linux-gnueabihf
import path[1] = /usr/include/d/4.9
import path[2] = /home/pi/vk/source
import path[3] = /root/.dub/packages/ncurses-master/source
gdc failed with exit code 1.
pi@rpi:~/vk $
`

**Comment by substanceof** [comment]
Их стало реально больше

**Comment by DTsurkov** [comment]
Кого их? Провальная затея или есть шанс собрать ваш клиент под арм?

**Comment by substanceof** [comment]
Ошибок. Я последний раз фиксил сборку под ldc, кажется, версию назад и проблем было немного. Как доберусь и посмотрю лично - скажу насчет шансов

**Comment by butaford** [comment]
Шансов нет я так понимаю ? Я очень бы хотел собрать под armv5tel (armel). Реально ли?
