### ISSUE TITLE
Проблема с входом!!!!

### ISSUE THREAD

**Issue by slava8686** [vk-cli/vk#113]
Logging in..
Rosa Linux
files.spec
Summary:	A console client for vk.com
Name:		vk-cli
Version:	0.7.6
Release:	1
License:	Apache-2.0
Group:		Networking/Chat
Url:		https://github.com/vk-cli/vk
Source0:	https://github.com/vk-cli/vk/archive/%{version}.tar.gz?/vk-%{version}.tar.gz

BuildRequires:	dub
BuildRequires:	dmd >= 2.071
Requires:		ncurses >= 5.7
Requires:		curl
Recommends:		mpv >= 0.22.0	

%description
A console client for vk.com.

%files
%{_bindir}/vk

#------------------------------------------------------------------

%prep
%setup -qn vk-%{version}

%build
dub build

%install
install -Dm 0755 vk %{buildroot}%{_bindir}/vk

**Comment by substanceof** [comment]
Так а что со входом то?

**Comment by slava8686** [comment]
Logging in... И все! Может надо что то  настроить.?

**Comment by slava8686** [comment]
Набираю логин и пароль, а в ответ logging in и все,может надо что то до настроить

**Comment by Abzwingt** [comment]
То же самое. Пробовал отключать двухфакторную аутентификацию, не помогло. Код иногда приходит через смс,  иногда нет

**Comment by SmugglerSMR** [comment]
У кого-нибудь вышло залогониться?

**Comment by substanceof** [comment]
Нужен лог после зависания
`/tmp/vkcli-log/`

**Comment by substanceof** [comment]
И проверьте сперва, работает ли логин с git версии / билда с мастера

**Comment by FooBarrior** [comment]
maybe captcha
