### ISSUE TITLE
Вообще будет работать?

### ISSUE THREAD

**Issue by chetnuy** [vk-cli/vk#116]
Устанавливал из yaourt. Пакет собрался на третий раз, возникали ошибки линковки. В результате не смог войти у учетку.
Потом поставил оттуда же git версию. Смог зайти на учетку. Но клиент виснет на любой из вкладок и начинает грузить процессор.

**Comment by substanceof** [comment]
Чертовски информативный тикет.
Нужен лог после зависания на гит версии: `/tmp/vkcli-log`

**Comment by chetnuy** [comment]
На сборке git из yaourt также возникает ошибка:
_.dub/build/release-shared-debug-linux.posix-x86_64-dmd_2079-B61C1F5CD3C99C388E58A4182962F6B1/vk.o: In function `_Dmain':
/tmp/yaourt-tmp-nevernew/aur-vk-cli-git/src/vk/source/app.d:1290: undefined reference to `_D9vkversion14currentVersionxAya'
.dub/build/release-shared-debug-linux.posix-x86_64-dmd_2079-B61C1F5CD3C99C388E58A4182962F6B1/vk.o: In function `_D5utils7initdbmFZv':
/tmp/yaourt-tmp-nevernew/aur-vk-cli-git/src/vk/source/utils.d:84: undefined reference to `_D9vkversion14currentVersionxAya'
collect2: ошибка: выполнение ld завершилось с кодом возврата 1
Error: linker exited with status 1
_
