### ISSUE TITLE
Ошибка при установке на Arch

### ISSUE THREAD

**Issue by xardover** [vk-cli/vk#119]
==> Запускается build()...
Running pre-generate commands for vk...
version string: 0.7.6
Performing "debug" build using /usr/bin/dmd for x86_64.
ncurses ~master: target for configuration "minimal" is up to date.
vk ~makepkg: building configuration "release-shared"...
Reticulating splines...
Linking...
.dub/build/release-shared-debug-linux.posix-x86_64-dmd_2080-A3235A8FDC53049A0700443C6FD88BFD/vk.o: In function `_Dmain':
/tmp/yaourt-tmp-xardover/aur-vk-cli/src/vk/source/app.d:1274: undefined reference to `_D9vkversion14currentVersionxAya'
.dub/build/release-shared-debug-linux.posix-x86_64-dmd_2080-A3235A8FDC53049A0700443C6FD88BFD/vk.o: In function `_D5utils7initdbmFZv':
/tmp/yaourt-tmp-xardover/aur-vk-cli/src/vk/source/utils.d:86: undefined reference to `_D9vkversion14currentVersionxAya'
collect2: ошибка: выполнение ld завершилось с кодом возврата 1
Error: linker exited with status 1
/usr/bin/dmd failed with exit code 1.
==> ОШИБКА: Произошел сбой в build().
    Прерывание...
==> ОШИБКА: Makepkg не смог собрать vk-cli.
==> Перезапустить сборку vk-cli ? да/Нет [y/N]
==> ------------------------------------------

После перезапуска устанавливается нормально

**Comment by substanceof** [comment]
После перезапуска системы?

**Comment by xardover** [comment]
После перезапуска сборки как предлагает yaourt

**Comment by substanceof** [comment]
Ну в первый раз не сраслось просто, бывает *kappa*
На деле фиксить тут нечего, странный баг, похоже, что dmd
