### ISSUE TITLE
Падает при перемешивании музыки

### ISSUE THREAD

**Issue by Weypare** [vk-cli/vk#37]
При нажатии на 'M' проходит секунда, интерфейс пропадает и появляется, как я понимаю, неполный crash log:
![crash](https://cloud.githubusercontent.com/assets/17096718/17604858/44a2bf64-6020-11e6-8660-23e6d5803fc8.png)

**Comment by HaCk3Dq** [comment]
Жди пока 0.8

Там все переделаем грамотно, будет айс

**Comment by Weypare** [comment]
Да, и ещё вопросик: а можете добавить поиск по аудиозаписям? Было бы очень полезно.

**Comment by HaCk3Dq** [comment]
В 0.8 будет

**Comment by sirikid** [comment]
Фикса не будет в связи с переписыванием приложения с нуля.
