### ISSUE TITLE
В музыке можно  выбрать пустую строку.

### ISSUE THREAD

**Issue by Vovano** [vk-cli/vk#40]
vk-cli 0.7.4
Зайти в программу и выполнить действия:
3 -> k -> l 
Результат:
core.exception.RangeError@source/app.d(896): Range violation

Разяснение: 
1. Перейти в вкладку с музыкой.
2. С первой песни листнуть вверх на одну позицию, чем пролистать список музики до конца и поставить выделение в последнюю строку экрана.
3. В моем случае  9 последних строк не содержат музыки, попытка их воспроизведения приводит к ошибке.

**Comment by HaCk3Dq** [comment]
Да, это известный баг
Сейчас переписываем полностью бекэнд и фронтэнд, так что подожди пока 0.8

**Comment by sirikid** [comment]
Фикса не будет в связи с переписыванием приложения с нуля.
