### ISSUE TITLE
Проверять конфиг на корректность  и правильность ключей

### ISSUE THREAD

**Issue by vitaly-zdanevich** [vk-cli/vk#52]
`std.utf.UTFException@/usr/include/dmd/phobos/std/utf.d(1219):  Invalid UTF-8 sequence (at index 1)`

Xubuntu 14.04 i386

**Comment by sirikid** [comment]
мне кажется или это уже было?

**Comment by HaCk3Dq** [comment]
@sirikid, возможно

**Comment by vitaly-zdanevich** [comment]
но ведь не запускается на 32-х разрядной системе?

**Comment by substanceof** [comment]
Какая версия клиента и как устанавливал?

**Comment by substanceof** [comment]
И скинь полный стектрейс

**Comment by vitaly-zdanevich** [comment]
0.7.4, распаковал из архива (все равно deb только распаковывает без создания глобального линка и в менеджере пакетов показывает нулевой размер).

std.utf.UTFException@/usr/include/dmd/phobos/std/utf.d(1219): Invalid UTF-8 sequence (at index 1)
                                                                                                 ----------------
                                                                                                                 ??:? pure dchar std.utf.decodeImpl!(true, 0, immutable(char)[]).decodeImpl(ref immutable(char)[], ref uint) [0x83165b7]
                                                                         ??:? pure @trusted dchar std.utf.decode!(0, immutable(char)[]).decode(ref immutable(char)[], ref uint) [0x8316541]
                            ??:? pure @property @safe dchar std.range.primitives.front!(immutable(char)).front(immutable(char)[]) [0x831649e]
                                                                                                                                             ??:? pure @safe immutable(char)[] std.string.stripLeft!(immutable(char)[]).stripLeft(immutable(char)[]) [0x834b537]
                                                                                                 ??:? pure @safe immutable(char)[] std.string.strip!(immutable(char)[]).strip(immutable(char)[]) [0x834b505]
                                             ??:? immutable(char)[][immutable(char)[]] cfg.load() [0x8361172]
                                                                                                             ??:? _Dmain [0x83136f3]
                                                                                                                                    ??:? _D2rt6dmain211_d_run_mainUiPPaPUAAaZiZ6runAllMFZ9__lambda1MFZv [0x83acc8a]
                                                    ??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x83acbdc]
                ??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).runAll() [0x83acc46]
                                                                                                                     ??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x83acbdc]
                                                                                 ??:? _d_run_main [0x83acb6e]
                                                                                                             ??:? main [0x83610e3]
                                                                                                                                  ??:? __libc_start_main [0xb7593af2]

**Comment by sirikid** [comment]
```
std.utf.UTFException@/usr/include/dmd/phobos/std/utf.d(1219): Invalid UTF-8 sequence (at index 1)
 ----------------
??:? pure dchar std.utf.decodeImpl!(true, 0, immutable(char)[]).decodeImpl(ref immutable(char)[], ref uint) [0x83165b7]
??:? pure @trusted dchar std.utf.decode!(0, immutable(char)[]).decode(ref immutable(char)[], ref uint) [0x8316541]
??:? pure @property @safe dchar std.range.primitives.front!(immutable(char)).front(immutable(char)[]) [0x831649e]
??:? pure @safe immutable(char)[] std.string.stripLeft!(immutable(char)[]).stripLeft(immutable(char)[]) [0x834b537]
??:? pure @safe immutable(char)[] std.string.strip!(immutable(char)[]).strip(immutable(char)[]) [0x834b505]
??:? immutable(char)[][immutable(char)[]] cfg.load() [0x8361172]
??:? _Dmain [0x83136f3]
??:? _D2rt6dmain211_d_run_mainUiPPaPUAAaZiZ6runAllMFZ9__lambda1MFZv [0x83acc8a]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x83acbdc]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).runAll() [0x83acc46]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x83acbdc]
??:? _d_run_main [0x83acb6e]
??:? main [0x83610e3]
??:? __libc_start_main [0xb7593af2]
```

**Comment by substanceof** [comment]
@vitaly-zdanevich попробуй удалить `.vkrc` в домашней папке

**Comment by vitaly-zdanevich** [comment]
помогло, спасибо

**Comment by sirikid** [comment]
Закрываем?

**Comment by vitaly-zdanevich** [comment]
так может стоит поправить исходники для будущих пользователей?

**Comment by sirikid** [comment]
@vitaly-zdanevich логично

**Comment by substanceof** [comment]
Такая ошибка скорее всего означает наличие несуществующего ключа в конфиге
