### ISSUE TITLE
Смена основного цвета

### ISSUE THREAD

**Issue by bcskda** [vk-cli/vk#59]
```
vk-cli 0.7.4--cc2b2ca
gnome-terminal 3.18.3
```
![2016-12-04 17-45-47](https://cloud.githubusercontent.com/assets/19408762/20866910/e2d1cb9a-ba51-11e6-8516-2fcfc1b069a9.png)
Возникает только при переходе с серого на белый

**Comment by substanceof** [comment]
Хотя я не думаю, что он будет фиксить))

**Comment by HaCk3Dq** [comment]
@substanceof *коммент про 0.8*

**Comment by substanceof** [comment]
Не закрывай хоть для приличия хд
