### ISSUE TITLE
Парсить аудио из html

### ISSUE THREAD

**Issue by upisfree** [vk-cli/vk#60]
Можно через эмуляцию браузера запариться и сделать аудио, думаю. Не рассматривал такой вариант?

**Comment by substanceof** [comment]
Парсить хтмл - дело неблагодарное. Да и авторизацию через oauth не перекинуть на веб версию. Посмотрим

**Comment by upisfree** [comment]
@substanceof нет, не парсить хтмл, а именно эмулировать поведение пользователя, управляя браузером. Selenium там какой-нибудь.

**Comment by sirikid** [comment]
@upisfree имхо оверкилл

**Comment by substanceof** [comment]
@upisfree 

> управляя браузером
Точно нет

**Comment by FlyInk13** [comment]
Могу подсказать как получить токен с доступом к аудио через авторизацию как в официальном приложении.

**Comment by HaCk3Dq** [comment]
@FlyInk13 офк, давай)

**Comment by FlyInk13** [comment]
Первым делом отправляем GET запрос с полями username и password.
https://oauth.vk.com/token?grant_type=password&scope=all&client_id=2274003&2fa_supported=1&client_secret=hHbZxrka2uZ6jB1inYsH

Возможные ошибки:
1) need_validation при validation_type=2fa_sms - 2х факторная авторизация
для отправки кода необходимо выполнить post запрос 
https://api.vk.com/method/auth.validatePhone?api_id=2274003&sid=${validation_sid}
Потом повторить запрос авторизации с дополнительным полем code.
2) need_captcha - требует код с картинки, тут объяснять думаю не надо.

Еще need_validation может быть когда заходишь с необычного места, тогда просто нужно с того же ip перейти по ссылке указанной в redirect_uri.

**Comment by substanceof** [comment]
Не требуется, пока что, в силу более или менее живого апи
