### ISSUE TITLE
Чтение по 2x enter в сообщениях

### ISSUE THREAD

**Issue by OlegWock** [vk-cli/vk#62]
Пришло 2 сообщения в конференции, но после входа (просмотра) диалога сообщения не отмечаются прочитанными. Ни после двойного Enter'а, ни после R ничего не меняется. (Терминал стандартный на убунте). Прога последней версии, зависимости тоже

```
➜ uname -a
Linux pikapika 4.4.0-47-generic #68~14.04.1-Ubuntu SMP Wed Oct 26 19:41:45 UTC 2016 i686 athlon i686 GNU/Linux
➜ echo $TERM
xterm
```

**Comment by substanceof** [comment]
На данный момент они читаются только после отправки сообщения

**Comment by OlegWock** [comment]
Планируется возможность добавить такую функцию? (Отдельной клавишей, например)

**Comment by substanceof** [comment]
Вообще планировалось на двойной энтер. Если у меня получится кое-кого заставить открыть эдитор на 0.7 ветке, то такая возможность даже появится

**Comment by HaCk3Dq** [comment]
@substanceof зачем эдитор? я же тебе обьяснял, что если я закрываю сессию курсов и востанавливаю, то все идет по пизде.
Дабл enter изи, сделай метод и я запилю

**Comment by substanceof** [comment]
fix: #85
