### ISSUE TITLE
Привязка к нотифай-менеджерам

### ISSUE THREAD

**Issue by mikhailnov** [vk-cli/vk#63]
Очень не хватает такой настройки.

**Comment by SerjAntiquity** [comment]
лучше notify-send опционально.

**Comment by mikhailnov** [comment]
а лучше и то, и другое с возможностью включать по-отдельности

**Comment by sirikid** [comment]
Что бы пищал ~~и все портил~~?
@substanceof @HaCk3Dq предлагаю реализовать уведомления посредством отправки терминалу управляющей последовательности [`\a`](https://ru.wikipedia.org/wiki/%D0%A3%D0%BF%D1%80%D0%B0%D0%B2%D0%BB%D1%8F%D1%8E%D1%89%D0%B8%D0%B5_%D1%81%D0%B8%D0%BC%D0%B2%D0%BE%D0%BB%D1%8B#.D0.A3.D0.BF.D1.80.D0.B0.D0.B2.D0.BB.D1.8F.D1.8E.D1.89.D0.B8.D0.B5_.D1.81.D0.B8.D0.BC.D0.B2.D0.BE.D0.BB.D1.8B_ASCII)

**Comment by SerjAntiquity** [comment]
через beep же надо делать 👍

**Comment by substanceof** [comment]
Не нужно
Если очень хочется - можно настроить звук в демоне нотифаев

**Comment by HaCk3Dq** [comment]
Нотифаи точно будем прикручивать, а дальше сами

**Comment by HaCk3Dq** [comment]
@sirikid наркоман, штоле?)

**Comment by SerjAntiquity** [comment]
@HaCk3Dq зато последнее слово за ним осталось)

**Comment by sirikid** [comment]
@HaCk3Dq сначала хотел кинуть в проект 0.8 но потом вспомнил что ишью о звуковых уведомлениях, а мы будем прикручивать notify-send

**Comment by HaCk3Dq** [comment]
@SerjAntiquity так переименуй и кинь в проект, кек

**Comment by sirikid** [comment]
@HaCk3Dq [алло](https://github.com/HaCk3Dq/vk/projects/2#card-1142209)
