### ISSUE TITLE
Excessive CPU usage

### ISSUE THREAD

**Issue by mikhailnov** [vk-cli/vk#64]
Грузит почти под 100% 1 ядро процессора при даже простое (музыка не играет, ничего не происходит, открыт в терминале фоном).

**Comment by sirikid** [comment]
Версию приложения, бинарник качал или сам собирал?

**Comment by substanceof** [comment]
Нужен лог

**Comment by mikhailnov** [comment]
Бинарник .deb готовый использую. Момент. когда начинается нагрузка, не отловил. Логи где у него? вывод strace нужен?

**Comment by mikhailnov** [comment]
Помню. вконтакте кто-то где-то тоже писал про нагрузку на процессор.

**Comment by HaCk3Dq** [comment]
@mikhailnov это было очень давно, во времена первого релиза, что собственно уже давно пофикшено и ты первый кто после этого жалуется)

**Comment by substanceof** [comment]
Логи в /tmp/vkcli-log

**Comment by sirikid** [comment]
Фикса не будет в связи с переписыванием приложения с нуля.
