### ISSUE TITLE
Не проходят неалфавитные символы в паролях при авторизации

### ISSUE THREAD

**Issue by TryKote** [vk-cli/vk#68]
При попытке авторизации вылетает следующее:

`Error while auth: {"error":"invalid_client","error_description":"Username or password is incorrect"}`

Первые 12 раз думал, что ввожу косячно, на 13 проверил с браузера -- все отлично.
![2016-12-24 00-16-51](https://cloud.githubusercontent.com/assets/7894035/21460904/c2c5ebd4-c96e-11e6-9e21-d7ee59272d25.png)

PS: vk-cli 0.7.5-1

**Comment by substanceof** [comment]
возможно, проблема с ncurses
Сколько символов в логине и пароле?

**Comment by pashinskikh** [comment]
Аналогичная проблема. Логин - почтовый ящик (26 символов), пароль - набор букв, цифр и символов (длинна - 20).
Возможно проблема из-за включенной двухэтапной аутентификации.

**Comment by substanceof** [comment]
@pashinskikh с двухфакторкой выпадает совершенно другая ошибка

**Comment by pashinskikh** [comment]
@substanceof понял, буду надеется, что ее не увижу :)
Есть ли какие-то мысли по багу? Можно ли спрашивать про ЕТА?
Может я могу как-то помочь в отловке бага?

**Comment by substanceof** [comment]
Учитывая некоторые проблемы с приватностью самих паролей, довольно сложно получить проблемную строку и с ней дебажить. В этом проблема

**Comment by TryKote** [comment]
@substanceof пароль 6 символов: строчные, заглавные, цифры, символы. Логин: номер телефона. Если будут сложности в отлове бага, могу сменить пароль, а Вам отдать старый.

**Comment by TryKote** [comment]
Проблема решена. Пароль не должен содержать спецсимволов \/|,№;:^#@.

**Comment by substanceof** [comment]
Не-не, закрывать рано, надо это пофиксить хд

**Comment by scorpp** [comment]
workaround есть? не хочется пароль менять. я его потом запомнить не могу каждый раз :D

**Comment by substanceof** [comment]
@scorpp 
авторизироваться руками в браузере хд
ссылку составить как эта функция: https://github.com/HaCk3Dq/vk/blob/master/source/app.d#L313
все остальные действия описаны здесь: https://github.com/HaCk3Dq/vk/issues/70

**Comment by sirikid** [comment]
Фикса не будет в связи с переписыванием приложения с нуля.

**Comment by denizzzka** [comment]
Имхо, так не делается - вдруг кто-то захочет фиксить? Пусть открытые тикеты висят

**Comment by substanceof** [comment]
бля, этот я может пофикшу еще, не трогай

**Comment by denizzzka** [comment]
Затык, похоже, в том, что функции ncurses типа getnstr не могут в UTF-8

**Comment by denizzzka** [comment]
Был баг, связанный с выделением памяти под имя и пароль (починено в https://github.com/vk-cli/vk/pull/79) - попробуйте, может оно починилось?

**Comment by substanceof** [comment]
Сделаю логин до старта курсов

**Comment by substanceof** [comment]
В мастере готов логин из консоли (без курсов)
