### ISSUE TITLE
Падение при длинных заголовках и узком окне

### ISSUE THREAD

**Issue by Hummer12007** [vk-cli/vk#69]
К примеру,  "🎄новогодняя танина шарага🎄и предновогодняя *уета" (без елочек не падает (или тоже падает)).

Это на мастере от 4 декабря, но вроде с того времени ничего не должно было поменяться.
UPD: на последнем тоже.

Ошибка: https://paste.pound-python.org/show/v333QPxtMP763niFaNWu/, терминал в 73 столбика.

(Падение в списке Conversations).

**Comment by sirikid** [comment]
Фикса не будет в связи с переписыванием приложения с нуля.
