### ISSUE TITLE
Показ изображений?

### ISSUE THREAD

**Issue by denizzzka** [vk-cli/vk#76]
Есть вот такая штучка:

http://code.dlang.org/packages/bearlibterminal

Она может.

Например, проверять наличие переменной окружения DISPLAY и если она есть то запускать ввод-вывод с картинками через неё.

**Comment by HaCk3Dq** [comment]
Это ведь враппер для BearLibTerminal, а он умеет только в "bitmap and vector (TrueType) fonts", что помогает писать рогалики.

Мимо кассы

**Comment by denizzzka** [comment]
@HaCk3Dq судя по скриншоту оно может и картинки:

![Image](http://foo.wyrd.name/_media/en:bearlibterminal:demo03.png)

**Comment by HaCk3Dq** [comment]
Это шрифты + отдельный терминал
Зачем вообще советовать не разобравшись?

**Comment by denizzzka** [comment]
> Это шрифты + отдельный терминал

Да нет же! Это возможность в шрифтовой сетке выводить картинки любых размеров!

> Зачем вообще советовать не разобравшись?

Ну хз, как хотите

**Comment by HaCk3Dq** [comment]
@denizzzka, да, но картинки мапятся на сетку как тайлы, читать [тут](http://foo.wyrd.name/en:bearlibterminal:design)

так что удобней открывать пикчи отдельным вьюером, например feh

**Comment by denizzzka** [comment]
удобней, но так было бы красиво. Ок, может руки дойдут запилю патч

**Comment by HaCk3Dq** [comment]
Я не уверен, что во всех терминалах это будет саппортиться, так что удачи)

**Comment by denizzzka** [comment]
Оно вообще не для терминалов - оно в честное Иксовое окно OpenGLом выводит имитацию терминальных буковок. Ну и картинки может.

**Comment by substanceof** [comment]
Зачем опенглное окно для консольного клиента?

**Comment by denizzzka** [comment]
> Зачем опенглное окно для консольного клиента?

Опциональное.

Те, кто открывает клиента в X11 и оставляет его надолго включенным в отдельном окне терминала - оценят.

**Comment by substanceof** [comment]
Основная его суть в том, чтобы работать в терминале и быть максимально миниатюрным, а не тянуть за собой зависимости для работы опенгла.
С гораздо большим успехом можно было бы писать клиент под гтк, чем крутить сбоку ьакие невнятные костыли и по десять раз дублировать код рисования гуев:  мало ли, кто еще какое окно захочет/прикрутит

**Comment by denizzzka** [comment]
> Основная его суть в том, чтобы работать в терминале и быть максимально миниатюрным

В 64 килобайтах сидите?

> по десять раз дублировать код рисования гуев

Если не говнокодить то всё норм впишется

**Comment by pvarenik** [comment]
@denizzzka так ты же патч грозился сделать :) я бы на самом деле глянул just for fun.

**Comment by denizzzka** [comment]
Если занят не буду, и надо дождаться когда это https://github.com/Elronnd/bearlibterminal-dlang/issues/1 пофиксят

**Comment by pvarenik** [comment]
Подписался, буду альфатестером

**Comment by denizzzka** [comment]
Памятка: сделать превьюшки принудительно 256-цветными, с подбором палитры - будет лампово

**Comment by substanceof** [comment]
> не говнокодить
К курсам и этому чуду явно разный подход. Код рисования и взаимодействия в любом случае будет разный, даже есди ты очень веришь, что можно иначе.
Даже если собираешься делать патч, то делать его на ветку с 0.7 - бесполезно. Она сейчас практиески не поддерживается.

**Comment by denizzzka** [comment]
А какая поддерживается?

**Comment by HaCk3Dq** [comment]
Делаем 0.8 на rust

**Comment by denizzzka** [comment]
> Делаем 0.8 на rust

Этот ваш Rust... В D-версии какая ветка актуальна?

(Хотя было бы неплохо иметь один общий модуль доступа к API vk)

**Comment by denizzzka** [comment]
видел некоторое дерьмо:
```D
  // === this method is full of magic, do not touch ===

  print("Username (email or phone): ");
  char uname;
  echo; getstr(&uname); noecho;
  string strusr = (cast(char*)&uname).to!string;
```

**Comment by denizzzka** [comment]
@pvarenik я забил на это дело. Если хочешь можешь продолжить, оно выложено тут:
https://github.com/denizzzka/vk/tree/adds_bearlibterminal

Суть там вот в чём: сделана попытка эмуляции ncurses средствами bearlib (в этом файле, там всё понятно: https://github.com/denizzzka/vk/blob/adds_bearlibterminal/source/terminal/terminal.d)

Это всё собирается с помощью команды:
``$ dub --config=BearLibTerminal``

Но ещё нужно положить в систему бинарную библиотеку этого самого bearlibterminal (она входит в комплектацию дишного пакета)

Код vk так себе: всякие магические числа, куча вычислений позиций курсора и прочее такое - мне не понравилось. Эмуляция ncurses сходу заработала плохо, разбираться после увиденного внутри vk кажется бессмысленным, проще переписать с нуля по-нормальному. Если это кому-то надо.
