### ISSUE TITLE
killed by signal 11 macOS  Sierra

### ISSUE THREAD

**Issue by basson** [vk-cli/vk#78]
При запуске появляется запрос` Username (email or phone):` нажимаю любую клавишу и вылетает ошибка:
![2017-02-25 22 52 04](https://cloud.githubusercontent.com/assets/2330984/23332970/5525f152-fbad-11e6-9c67-1b1d4ffff391.png)
Это если собирать с мастер ветки приложение. А если собирать с 0.7.5 то на стадии сборки вылетает это: 
![2017-02-25 22 52 23](https://cloud.githubusercontent.com/assets/2330984/23332981/7207351a-fbad-11e6-96d1-aa24efc0b19f.png)

П.с пробовал и bash и zsh и 3 терминала (Treminal, iTerm2, Hyper)

**Comment by denizzzka** [comment]
Это мой косяк, привнесён тут:
https://github.com/vk-cli/vk/pull/77/commits/c7811cbde2d510a3da77927ef2dda308db02239b

**Comment by basson** [comment]
Спасиб откатил изменения помогло. Один вопрос цвета настроить как то можно?

**Comment by denizzzka** [comment]
(Сейчас исправлю)
