### ISSUE TITLE
Не удается вставить символ ¯\_(ツ)_/¯ в диалог

### ISSUE THREAD

**Issue by marimysh** [vk-cli/vk#81]
1. Скопипасчен символ ¯\_(ツ)_/¯. 
2. После ctrl+shift+v получилось ¯\_(ツM-/)_/
3. При попытке удалить M-/ выдается следующий текст в поле ввода: 

> ¯\_(ツM-/std.utf.UTFException@/usr/include/dlang/dmd/std/utf.d(1217): Invalid UTF-8 sequence (at index 1)
>                              ----------------
>                                              ??:? pure dchar std.utf.decodeImpl!(true, 0, immutable(char)[]).decodeImpl(ref immutable(char)[], ref ulong) [0x71ba14]
>         ??:? pure @trusted dchar std.utf.decode!(0, immutable(char)[]).decode(ref immutable(char)[], ref ulong) [0x71b98e]
>                                             ??:? pure @property @safe dchar std.range.primitives.front!(immutable(char)).front(immutable(char)[]) [0x71b8d4]
>                                                                              ??:? pure @safe void std.array.Appender!(immutable(wchar)[]).Appender.put!(immutable(char)[]).put(immutable(char)[]) [0x7598ef]
>                                                 ??:? pure @safe immutable(wchar)[] std.conv.toImpl!(immutable(wchar)[], immutable(char)[]).toImpl(immutable(char)[]) [0x758fd9]
>                    ??:? pure @safe immutable(wchar)[] std.conv.to!(immutable(wchar)[]).to!(immutable(char)[]).to(immutable(char)[]) [0x758fa7]
>                                                                 ??:? void app.msgBufferEvents() [0x711d06]
>                             ??:? void app.controller() [0x711ac0]
>                                                                  ??:? _Dmain [0x716e6b]
>          ??:? _D2rt6dmain211_d_run_mainUiPPaPUAAaZiZ6runAllMFZ9__lambda1MFZv [0x7b81fa]
>          ??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x7b8140]
>                                                      ??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).runAll() [0x7b81b6]
>                                                                            ??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x7b8140]
>                                          ??:? _d_run_main [0x7b80ba]
>                                                                     ??:? main [0x77d7c9]
>           ??:? __libc_start_main [0x7eb4e510]

4. Удалить или отредактировать ничего не получается. Также не переходит в меню. На Q приложение также не реагирует. После закрытия сигналом ctrl+c открывается снова нормально с пустым полем ввода

**Comment by marimysh** [comment]
Дополню. Если все же отправить вставленное, то... до VK оно не доходит. В консольном чате пишет, что отправлено. На деле нет.

**Comment by HaCk3Dq** [comment]
В 0.8 будет переписан режим ввода текста, пока что это не пофиксить
