### ISSUE TITLE
Нету музыки после обновления ВК

### ISSUE THREAD

**Issue by grozahn** [vk-cli/vk#83]
В списке треков есть только дорожка "Аудио доступно на vk.com - и в официальных приложениях ВКонтакте"

**Comment by x0wllaar** [comment]
ВК снова все сломали, надо смотреть, что там происходит, и как они различают официальное приложение и все остальные. Мое предположение - поменяли API ключ приложения на Android

**Comment by HaCk3Dq** [comment]
@x0wllaar +
придется все переделывать, либо вообще дропать консольный вк из-за музыки

**Comment by substanceof** [comment]
Пропала документация по апи аудио
Думаю, потребуется реверс одного из приложений

**Comment by f1u77y** [comment]
Ключ таки не поменяли, потому что VK Coffee, который давно не обновлялся, работает с аудио. Или я что-то делаю не так.

**Comment by x0wllaar** [comment]
По юзерагенту мож режут?

**Comment by HaCk3Dq** [comment]
скорее всего сторонним клиентам и музыке пизда
gg wp, маилсру

**Comment by grozahn** [comment]
Может всё таки парсить аудио из HTML?

**Comment by HaCk3Dq** [comment]
@grozahn можно попробовать

**Comment by cadaverosus** [comment]
Да, режут в том числе и по юзер-агенту.
Вот тут последними двумя коммитами обошли изменения в api: https://github.com/ga2mer/db-vk/

**Comment by x0wllaar** [comment]
@cadaverosus да, если поставить такой юзерагент, то музыка возвращается. Спасибо)

Сделал Pull

**Comment by substanceof** [comment]
fix: #85
