### ISSUE TITLE
Отображает что я онлайн. 

### ISSUE THREAD

**Issue by moonfor** [vk-cli/vk#84]
Отображает что онлайн с телефона, хотя send_online = false.

**Comment by moonfor** [comment]
Если еще раз меняю то скрывает, в общем при входе в vk-cli всегда показывает что онлайн.

**Comment by substanceof** [comment]
Теперь вк делает аккаунт онлайн при любом запросе к апи

**Comment by moonfor** [comment]
И обойти это нельзя ?

**Comment by substanceof** [comment]
Я, конечно, внимательно изучу любые предложения, но если разрабы вк нигде не накосячили - то нет, нельзя.
