### ISSUE TITLE
Крашится в коротких чатах

### ISSUE THREAD

**Issue by JackPraer** [vk-cli/vk#86]
![_2017-05-21_16-22-13](https://cloud.githubusercontent.com/assets/24777098/26284981/2bfce904-3e4f-11e7-9dcf-99f3f65da379.png)

**Comment by HaCk3Dq** [comment]
можно хотя бы описание как возникает краш, etc

**Comment by JackPraer** [comment]
когда опускаюсь в самый низ сообщений

**Comment by JackPraer** [comment]
крашится как оказалось не на последнем сообщении, а на одном единственном

**Comment by JackPraer** [comment]
Выслал костыль, чтобы пофиксить это дерьмо.
Fixed & Pulled.
