### ISSUE TITLE
Картинки

### ISSUE THREAD

**Issue by malyutinegor** [vk-cli/vk#88]
Здравствуйте!

Можете ли вы реализовать отображение картинок в вашем клиенте с помощью w3m, как это сделано в ranger?

Заранее спасибо за ответ.

**Comment by substanceof** [comment]
Довольно сложно для имплементации (осоюенно так, чтобы картиники скролились вместе с остальным). При этом не работает в современных терминалах, так что ценность такого функционала весьма сомнительна

**Comment by denizzzka** [comment]
> Можете ли вы реализовать отображение картинок в вашем клиенте с помощью w3m, как это сделано в ranger?

Можно подробнее?

**Comment by grozahn** [comment]
А можно попробовать реализовать картинки с помощью w3m-img. Если я не ошибаюсь, то так реализовано в том же ranger.
