### ISSUE TITLE
Краш при разделении окна терминатора

### ISSUE THREAD

**Issue by QuentinCaffeino** [vk-cli/vk#89]
При использовании терминала Terminator 1.91 крашится при разделении вертикально

`core.exception.RangeError@source/app.d(1104): Range violation
                      ----------------
                                      ??:? _d_arrayboundsp [0x7d84da]
                                                                     source/app.d:1104 app.ListElement[] app.GetDialogs() [0x718bcd]
                                               source/app.d:494 void app.bodyToBuffer() [0x71350c]
             source/app.d:1317 _Dmain [0x71a651]
                                                ??:? _D2rt6dmain211_d_run_mainUiPPaPUAAaZiZ6runAllMFZ9__lambda1MFNlZv [0x7dcdc3]
                                           ??:? scope void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x7dccf3]
 ??:? scope void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).runAll() [0x7dcd6c]
                      ??:? scope void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x7dccf3]
                                                                 ??:? _d_run_main [0x7dcc63]
       ??:? main [0x783201]
                           ??:? __libc_start_main [0xf5bb582f]
`

**Comment by substanceof** [comment]
Скорее всего терминал с клиентом стал слишком маленьким

**Comment by JackPraer** [comment]
пофикшен 91 пулл реквестом
можно закрывать
