### ISSUE TITLE
Прокси

### ISSUE THREAD

**Issue by iwex** [vk-cli/vk#92]
Добавьте, пожалуйста, возможность настройки прокси для клиента

**Comment by HaCk3Dq** [comment]
@iwex пока что это вряд ли реализуем, важнее 0.8 выпустить, там может как-нибудь допилим

**Comment by iwex** [comment]
@HaCk3Dq просто для пользователей Украины немного проблемно использовать)

**Comment by pvarenik** [comment]
@iwex попробуй такую штуку (сам не пробовал) https://askubuntu.com/questions/583797/how-to-set-a-proxy-for-terminal

**Comment by grozahn** [comment]
Мне не помогло, получаю это:
