### ISSUE TITLE
macOS 10.12.5 build failed

### ISSUE THREAD

**Issue by Andrew-Hopper** [vk-cli/vk#93]
HEAD is now at 1578da1... release 0.7.5

Andrews-MBP:vk andrewhopper$ dub

Fetching ncurses ~master (getting selected version)...
Running pre-generate commands for vk...
version string: 0.7.5
Performing "debug" build using dmd for x86_64.
ncurses ~master: building configuration "minimal"...
vk ~master: building configuration "debug"...
source/app.d(1290,3): Deprecation: catch statement without an exception specification is deprecated; use catch(Throwable) for old behavior
source/utils.d(363,23): Error: undefined identifier 'SIGRTMIN'
source/utils.d(364,22): Error: undefined identifier 'SIGRTMIN'
Reticulating splines...
dmd failed with exit code 1.

**Comment by Andrew-Hopper** [comment]
В то же время мастер собрался, но с помощью: `LANG=C dub --force`

**Comment by x0wllaar** [comment]
??? ?????? ??? ?????? ?? ???????????? ??? ??????? (SIGRT*)
??? ????? ??? ????????????? ???????, ?? ? ????????? ????? ????? ?????????? ?????? ? ??? ?????? ?? ????? ??? ?????????? ??????
________________________________

**Comment by substanceof** [comment]
Последняя версия - 0.7.6. В ней это исправлено.
LANG нужен не для сборки, а для автоматического выбора языка в клиенте. Просто надо положить туда что-то вроде `en_US`.

**Comment by substanceof** [comment]
@x0wllaar кодировка)

**Comment by Andrew-Hopper** [comment]
@substanceof тогда исправьте инструкцию сборки на версию  0.7.6

**Comment by substanceof** [comment]
Ок
