### ISSUE TITLE
Пропала музыка

### ISSUE THREAD

**Issue by BigRedEye** [vk-cli/vk#95]
Пропала музыка, во вкладке Music ничего не отображается. Опять мейлы все поломали?
vk-cli 0.7.6, Ubuntu 16.04 LTS
![screenshot from 2017-08-12 15-05-27](https://user-images.githubusercontent.com/17150781/29240513-c19bbc90-7f6f-11e7-98f6-7a50ec8c7d76.png)

**Comment by tyusha0** [comment]
подтверждаю, правда собирал dub, dtools и vk-cli с помощью ldc, в archlinux32 dmd отказался собираться

**Comment by HaCk3Dq** [comment]
Да, музыка снова не пашет, пока что это не фиксили

**Comment by BigRedEye** [comment]
Кстати, вот тут https://github.com/python273/vk_api все работает, можно за основу взять. Вк, видимо, просто поломали url на аудио

**Comment by HaCk3Dq** [comment]
Глянем на досуге

**Comment by ga2mer** [comment]
TL;DR;
На API у поиска и получение списка с музыкой стоит проверка на лицензию через GCM, метод getById всё ещё работает. 
Музыка будет работать или на андроидах/ios или придётся парсить через сайтовое апи, у себя в плагине для deadbeef сделал, вроде даже не сломалось ещё
