### ISSUE TITLE
a problem with installation

### ISSUE THREAD

**Issue by EvaWeinreich** [vk-cli/vk#98]
root@x550c:/home/eva# cd vk
root@x550c:/home/eva/vk# git checkout 0.7.6
Note: checking out '0.7.6'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at a12ead4... mark 0.7.6

root@x550c:/home/eva/vk# dub build
Fetching ncurses ~master (getting selected version)...
Running pre-generate commands for vk...
/bin/sh: 1: rdmd: not found
Command failed with exit code 127

**Comment by HaCk3Dq** [comment]
собирай с мастера

**Comment by substanceof** [comment]
@HaCk3Dq ору

**Comment by substanceof** [comment]
```
dmd generateVersion.d
./generateVersion
```
потом удали строку 13 из `dub.json` (`  "preGenerateCommands": ["rdmd generateVersion.d"],`)
и снова сделай `dub duild`

**Comment by substanceof** [comment]
@EvaWeinreich 
```
dmd generateVersion.d
./generateVersion
```
потом удали строку 13 из _dub.json_ (`  "preGenerateCommands": ["rdmd generateVersion.d"],`)
и снова сделай `dub duild`
