### ISSUE TITLE
Автоматический запрос пароля, при "потере" токена

### ISSUE THREAD

**Issue by BANOnotIT** [vk-cli/vk#99]
Оказывается клиент не понимает, что нужно получить новый токен, когда старый перестаёт быть валидным.
Запрос пароля не происходит, после "завершения всех сеансов" с официального сайта. Может я конечно что не так делаю, но мне просто показывается пустой интерфейс с менюшкой. Никакого уведомления об ошибке и вообще никаких признаков ошибки. Помогает только удаление `.vkrc`.

**Comment by HaCk3Dq** [comment]
Все верно, так и есть

**Comment by BANOnotIT** [comment]
В смысле "так и есть"? Это далеко не ожидаемое поведение. Может его всё же стоит исправить?

**Comment by x0wllaar** [comment]
@HaCk3Dq не в обиду, но это лучший ответ на багрепорт в моей жизни:

- Наш дом горит! - Все верно, так и есть

- К планете приближается астероид диаметром 10 км! - Все верно, так и есть

- Вышедшие из-под контроля роботы уничножают все живое на своем пути! - Все верно, так и есть

Мой день сделан

**Comment by BANOnotIT** [comment]
@x0wllaar не знаю как у Вас, а у меня сейчас уже 11. А вообще нежданный ответ такой, хотя бы сказали бы: "мы знаем, репорт уже был" ну или ещё как, но не так.

**Comment by substanceof** [comment]
Сразу просить авторизацию не выйдет (из-за невозможности перезапустить сессию ncurses без процесса), но, думаю, можно просто класть клиент с соответствующим сообщением и спрашивать на следующем запуске

**Comment by HaCk3Dq** [comment]
@x0wllaar ахахахх)
топ юзкейсы :D

**Comment by bcskda** [comment]
@substanceof можно же: 0427fd6394fc229713f19261b4a8f4d50722eca7

**Comment by BANOnotIT** [comment]
@bcskda [это вот этот кусок?](https://github.com/bcskda/2ch-cli/commit/0427fd6394fc229713f19261b4a8f4d50722eca7#diff-62df04e68c992181ae5943ca85f5ed35L148) Просто я с ncurses не работал от слова совсем...

**Comment by substanceof** [comment]
@bcskda наверное заработает. Тут все таки еще есть биндинг для D, там может быть не все. Это к @hack3dq. Переавторизацию с вылетом я сделаю.

**Comment by bcskda** [comment]
@BANOnotIT ну да.
@substanceof на Си вроде ```delwin()``` на все окна и ```endwin()``` после достаточно, поэкспериментирую на D.
